---
# Preflight steps
- name: Install required packages
  ansible.builtin.dnf:
    state: present
    name: "{{ packages }}"
  vars:
    packages:
    - qemu-kvm
    - libvirt
    - virt-install
    - virt-viewer