name: CI

on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/ubi
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf install -y ansible-core ansible-lint yamllint
      - name: Run ansible-lint
        run: ansible-lint ansible_collections/rprakashg/vpac
        continue-on-error: true
      - name: Run yamllint
        run: yamllint
        continue-on-error: true
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/ubi
      options: --privileged
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Install ansible core
        run: |
          dnf install -y ansible-core python3
    
      - name: Install required ansible collections
        run: |
          ansible-galaxy collection install amazon.aws